"""
Quick demo script to test visualization with generated mission data.
"""

import sys
from pathlib import Path

# Add python directory to path (go up from examples to python dir)
python_dir = Path(__file__).parent.parent
sys.path.insert(0, str(python_dir))

import numpy as np
import matplotlib.pyplot as plt
import data_loader
import visualize_attitude


def main():
    # Path to the CSV file generated by C++ test
    csv_file = Path(__file__).parent.parent.parent / 'build' / 'mission_data.csv'
    
    print(f"Loading data from: {csv_file}")
    
    if not csv_file.exists():
        print("ERROR: mission_data.csv not found!")
        print("Please run the C++ test first:")
        print("  cd build")
        print("  .\\tests\\Release\\mission_test.exe --gtest_filter=MissionTest.FullMissionSimulation")
        return
    
    # Load and display info
    df = data_loader.load_simulation_data(csv_file)
    print(f"\nLoaded {len(df)} data points")
    print(f"Time range: {df['time'].iloc[0]:.1f}s to {df['time'].iloc[-1]:.1f}s")
    
    # Extract statistics
    quats = data_loader.extract_quaternions(df)
    rates = data_loader.extract_angular_rates(df)
    
    print(f"\nInitial angular rate: {rates[0]} rad/s (magnitude: {np.linalg.norm(rates[0]):.4f} rad/s)")
    print(f"Final angular rate: {rates[-1]} rad/s (magnitude: {np.linalg.norm(rates[-1]):.6f} rad/s)")
    
    # Check mode transitions
    if 'mode' in df.columns:
        unique_modes = df['mode'].unique()
        print(f"\nMission modes encountered: {unique_modes}")
        for mode_int in unique_modes:
            mode_name = data_loader.get_mode_name(mode_int)
            count = (df['mode'] == mode_int).sum()
            duration = count * (df['time'].iloc[1] - df['time'].iloc[0])
            print(f"  {mode_name} (mode {mode_int}): {count} samples, ~{duration:.1f}s")
    
    print("\nGenerating visualizations...")
    
    # Create time series plots
    print("  - Creating time series plots...")
    fig1, axes1 = visualize_attitude.plot_attitude_timeseries(str(csv_file))
    
    # Create 3D visualization at key moments
    print("  - Creating 3D visualization at final time...")
    fig2, ax2 = visualize_attitude.visualize_attitude_static(str(csv_file), time_index=-1)
    
    print("\n✓ Visualizations generated successfully!")
    print("\nClose the plot windows to exit...")
    plt.show()
    
    print("\nTo create an animation, run:")
    print(f"  cd python")
    print(f"  python visualize_attitude.py ../build/mission_data.csv --animate")


if __name__ == '__main__':
    main()
