"""
Simple example demonstrating attitude visualization from mission data.

This script loads mission data from the C++ simulation and creates
basic visualizations of the attitude.
"""

import sys
from pathlib import Path

# Add parent directory to path to import modules
sys.path.insert(0, str(Path(__file__).parent.parent))

import visualize_attitude
import data_loader


def main():
    """Main function to visualize mission data."""
    
    # Path to mission data CSV (generated by C++ mission_test)
    csv_file = "mission_data.csv"
    
    # Check if file exists
    if not Path(csv_file).exists():
        print(f"Error: {csv_file} not found!")
        print("Please run the C++ mission test first to generate the data:")
        print("  cd build")
        print("  ctest -C Release -R MissionTest --output-on-failure")
        return
    
    print("Loading mission data...")
    df = data_loader.load_simulation_data(csv_file)
    print(f"Loaded {len(df)} data points spanning {df['time'].iloc[-1]:.1f} seconds")
    
    # Show statistics
    quats = data_loader.extract_quaternions(df)
    rates = data_loader.extract_angular_rates(df)
    
    print(f"\nAttitude Statistics:")
    print(f"  Initial angular rate: {rates[0]} rad/s (norm: {np.linalg.norm(rates[0]):.3f})")
    print(f"  Final angular rate: {rates[-1]} rad/s (norm: {np.linalg.norm(rates[-1]):.3f})")
    
    if 'mode' in df.columns:
        print(f"\nMission Modes:")
        for mode_int in df['mode'].unique():
            mode_name = data_loader.get_mode_name(mode_int)
            count = (df['mode'] == mode_int).sum()
            print(f"  {mode_name}: {count} samples")
    
    # Create visualizations
    print("\nGenerating visualizations...")
    
    print("  1. Static 3D view at final time...")
    fig1, ax1 = visualize_attitude.visualize_attitude_static(csv_file, time_index=-1)
    
    print("  2. Attitude time series...")
    fig2, axes2 = visualize_attitude.plot_attitude_timeseries(csv_file)
    
    print("\nDisplaying plots (close windows to exit)...")
    import matplotlib.pyplot as plt
    plt.show()
    
    print("\nTo create an animation, run:")
    print(f"  python visualize_attitude.py {csv_file} --animate")


if __name__ == '__main__':
    import numpy as np
    main()
